name: Install .bashrc
on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
      - name: Check current dir
        run: pwd
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare for installation
        run: chmod +x ./install.sh
      - name: Check dir
        run: ls -al
      - name: Install .bashrc
        run: |
          source .bashrc

